### ISSUE TITLE
Use HEEx to define templates

### ISSUE THREAD

**Issue by cblavier** [phenixdigital/phoenix_storybook#124]
Templates are currently defined as raw strings. HEEx would be probably be a better choice

**Comment by cblavier** [comment]
Sorry, I missed your comment.
No, it's still unsolved. Templates defined in stories such as:

```elixir
def template do
  """
  <div class="my-custom-wrapper">
    <.lsb-variation/>
  </div>
  """
end
```
are plain binaries. It'd better as HEEx templates, not trivial tho

**Comment by zoedsoupe** [comment]
I'll try to solve this, although I can't promise
