### ISSUE TITLE
Fix CSP support

### ISSUE THREAD

**Issue by crkent** [phenixdigital/phoenix_storybook#149]
Code highlighting breaks for applications which set CSPs. This is due to the use of an inline style element to add (Makeup-generated) highlighting.

https://github.com/phenixdigital/phx_live_storybook/blob/a6a8c6beae69fa30f96083acd4cf33b1fc54edea/lib/phx_live_storybook/templates/layout/root.html.heex#L28-L30

To fix this, the simplest solution could be to add support for a [nonce](https://content-security-policy.com/nonce/) parameter from the conn. Happy to submit a pull request for this, if desired.

**Comment by cblavier** [comment]
Hey Carson, I wasn't really aware of CSP, thanks for raising this issue.
Please open a PR

**Comment by cblavier** [comment]
👋 @crkent still wanna open a PR on this topic?

**Comment by gaiabeatrice** [comment]
Hi @cblavier, congrats on this super cool library, I absolutely love it!

I was wondering if there is a reason this got closed. I am still getting this.

## How to replicate
Make sure the `:browser` pipeline in the router includes CSP headers
```elixir
  pipeline :browser do
    # other plugs
    plug :put_secure_browser_headers, %{"content-security-policy" => "default-src 'self'"}
  end
```
The code snippets won't load the syntax highlighting:
<img width="802" alt="Screenshot 2022-12-27 at 11 33 08 AM" src="https://user-images.githubusercontent.com/11300729/209708152-f1d26fdb-f808-4c41-a145-5ab04d63fd06.png">

**Comment by gaiabeatrice** [comment]
Just to add more context, this is an issue Phoenix Live Dashboard was having as well, and the following discussion is very interesting to read to find a similar solution.
https://github.com/phoenixframework/phoenix_live_dashboard/issues/183

**Comment by cblavier** [comment]
Thanks for your feedback, Beatrice.
I closed the issue because I had no news from @crkent 

I will reopen it, and get it fixed!

**Comment by gaiabeatrice** [comment]
Beatrice is my last name, I go by Gaia 😁 

Let me know if you need help, I can probably whip up a PR if needed.

**Comment by cblavier** [comment]
Sorry about that, Gaia :)
I would gladly take a PR and review it, thanks for proposing.

**Comment by cblavier** [comment]
Hey Gaia, still want to open a PR? Need any help?
Let me know!

**Comment by cblavier** [comment]
No that's fine!
I'm still aiming at a 0.5.0 release by the end of the month

**Comment by Papipo** [comment]
Why was this closed? I am having this issue in the latest version.

**Comment by cblavier** [comment]
This was closed by lack of external contribution 🤷‍♂️

I'd be more than happy to receive a PR on the topic, I don't know anything about CSP

**Comment by gaiabeatrice** [comment]
Hi sorry for the enormous and inexcusable delay.

I came back to work on this and I am having some issues with some inline styles. I can still open the PR, so someone more expert on the frontend can maybe help.

**Comment by cblavier** [comment]
Thanks a lot, @gaiabeatrice 🙏🙏🙏
It helped me a lot in understanding what CSP and nonces are.

I also had issues with favicons, but I fixed it by allowing `self` in the `img-src` directive in my policy as such:
```
img-src 'self' 'nonce-#{img_nonce}'
```
From my understanding, the nonce should have been enough, but anyway, that did the trick.
