### ISSUE TITLE
Improve readability of attribute documentation

### ISSUE THREAD

**Issue by ArthurClemens** [phenixdigital/phoenix_storybook#180]
For some attributes, the displayed documentation is almost unreadable.

Rendered in phx_live_storybook:

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/350303/201535014-daffbeed-1273-40f8-809d-a36a53bf42f1.png">

The same documentation generated by ExDoc:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/350303/201535046-6dcb2f62-d50a-4c9d-9d55-417caba39339.png">

---

Some suggestions:

- Documentation column
  - Render Markdown
  - Remove `max-width: 16rem` - this is far too small
  - Remove style `white-space: pre-line;`
- Column Default
  - Add style `white-space: break-spaces;`
  - Not styling per se, but the Value field cannot be edited when the value is a `map`

**Comment by cblavier** [comment]
I could indeed improve CSS, but I think that whatever I do, this won't render well in a table.
What do you think of truncating the doc to the first paragraph, and then click on it to expand full doc in a modal window?

There are also some redundant information: ExDoc generate documentation for default values, but this information is already visible in the next column

**Comment by ArthurClemens** [comment]
An expand option could work. Perhaps reveal it in an extra row below the current one.

**Comment by ArthurClemens** [comment]
I was thinking along these lines:

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/350303/201765718-6781e000-88a0-4506-9b38-f146bd2462e8.png">

**Comment by cblavier** [comment]
Fixed in #535 
(sorry for delay!)
