### ISSUE TITLE
Phoenix aliases need to be adjusted

### ISSUE THREAD

**Issue by LostKobrakai** [phenixdigital/phoenix_storybook#252]
The instructions should include updating the phoenix aliases for `assets.deploy` and `assets.build`, so css is available outside of development.

**Comment by cblavier** [comment]
Yes, I'll do that

**Comment by cblavier** [comment]
I will improve the generator to add:
- `"tailwind storybook --minify",` into `mix.exs` aliases
- `COPY storybook storybook` into `Dockerfile`
