### ISSUE TITLE
Question: How to add my own css resources?

### ISSUE THREAD

**Issue by jsolana** [phenixdigital/phoenix_storybook#253]
Hi!

I need to add my own css resources and the only way I found is adding directly [here](https://github.com/phenixdigital/phoenix_storybook/blob/main/lib/phoenix_storybook/templates/layout/root.html.heex#L31) this piece of code:

```elixir
<MyLibrary.stylesheet_links
      stylesheets={my_stylesheets()}
    />

```

Internally my library return something like that:

```elixir
 ~H"""
    <%= for path <- @stylesheets do %>
      <link rel="stylesheet" href="..." />
    <% end %>
    """
```
Is there another way?

Really appreciate your help. Thanks!!

**Comment by cblavier** [comment]
I think you should dynamically add the stylesheet from javascript.

For instance, you can do from your `assets/js/storybook.js`

```javascript
var link = document.createElement('link');
link.setAttribute('rel', 'stylesheet');
link.setAttribute('href', 'css/my.css');
document.head.appendChild(link);
```

I'm already doing something like that to load googlemaps js file for my stories

**Comment by jsolana** [comment]
The problem, this resources are provided by another elixir library. Is it possible?

**Comment by gaggle** [comment]
> I think you should dynamically add the stylesheet from javascript.
> 
> For instance, you can do from your `assets/js/storybook.js`
> 
> ```js
> var link = document.createElement('link');
> link.setAttribute('rel', 'stylesheet');
> link.setAttribute('href', 'css/my.css');
> window.onload = () => {
>   document.head.appendChild(link);
> }
> ```
> 
> I'm already doing something like that to load googlemaps js file for my stories

Thanks @cblavier, if others come across this issue looking for more specific examples I ended with adding this to `assets/js/storybook.js`:

```
window.onload = () => {
  const stylesheets = ["@vendor/foo/bar.css"];

  stylesheets.forEach(href => {
    const link = document.createElement('link');
    link.setAttribute('rel', 'stylesheet');
    link.setAttribute('phx-track-static', '');
    link.setAttribute('href', href);
    document.head.appendChild(link);
  });
};
```

It works. It's… a little odd? Certainly quite difficult to discover without coming across this specific issue 😅 Maybe an update to a guide to suggest this, or extend the lib so we can pass stylesheets into e.g. `use PhoenixStorybook`? But just thoughts, happy the above works.
