### ISSUE TITLE
allow for custom `handle_event` implementation in stories

### ISSUE THREAD

**Issue by tcoopman** [phenixdigital/phoenix_storybook#254]
I find that I'm using storybook not just for having a component library with documentation, but also to try components, interact with them,...

For some of the components I write it would be really nice if I could write a custom `handle_event` that could be used in the playground.
For example I'm writing a component where you can input tags and remove them again. Right now I can only render known states, but can't really interact with the component. By having an option for a custom `handle_event` implementation, that could be solved.
My idea is that the handle_event would return an altered variation.

**Comment by cblavier** [comment]
For now, I'm using another kind of story to demo interactive components: `example` stories.
Have you already tried them?

Another path to explore is using `JS.push("assign", ...)` such as in this story: 

https://phx-live-storybook-sample.fly.dev/storybook/components/templates/template_component?theme=default
