### ISSUE TITLE
Custom code snippet

### ISSUE THREAD

**Issue by sarasilvaworkera** [phenixdigital/phoenix_storybook#275]
Hello!

I just wanted to understand if it's possible to customize the code preview snippet and the code section on the playground as needed. Right now I have something generated like this:

`<.render cta_link="https://test/" cta_text="Call to action" description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid pariatur, ipsum similique veniam." title="Default/Info message"/>`

but actually what I want is for it to be showcased in these sections like:

`<MyComponentLibrary.ComponentName cta_text="Call to action" description="Lorem ipsum ..." title="Title" />`

**Comment by cblavier** [comment]
To achieve what you want, you need to define your story function as `& MyComponentLibrary.ComponentName/1` and not `render/1`

**Comment by sarasilvaworkera** [comment]
Sorry the delay and not sure if I understood, but right now I have this function defined as
`  def function, do: &App.Shared.Components.NewButton.button/1`

and I get this in the storybook:
<img width="286" alt="image" src="https://github.com/phenixdigital/phoenix_storybook/assets/117083011/621ac726-a063-421f-b426-6185eac9fddc">

when actually what I wanted was something like:

`<App.Shared.Components.NewButton.button ...>`

how do I achieve this?
