### ISSUE TITLE
Elixir 1.15.0 support

### ISSUE THREAD

**Issue by shirishgoyal** [phenixdigital/phoenix_storybook#308]
For elixir 1.15.0, below deprecated warnings are being shown

https://github.com/phenixdigital/phoenix_storybook/blob/f09b3cb3a1323b3a41da631229c9962022b45021/lib/phoenix_storybook/rendering/component_renderer.ex#L151

1) ```
warning: :aliases option in eval is deprecated
  (elixir 1.15.0) src/elixir.erl:275: :elixir.env_for_eval/1
  (elixir 1.15.0) lib/code.ex:998: Code.eval_quoted/3
  (phoenix_storybook 0.5.4) lib/phoenix_storybook/rendering/component_renderer.ex:151: PhoenixStorybook.Rendering.ComponentRenderer.render_component_heex/3
  (phoenix_storybook 0.5.4) lib/phoenix_storybook/live/story_live.ex:419: anonymous fn/3 in PhoenixStorybook.StoryLive.render_content/2
```

2) ```
warning: :requires option in eval is deprecated
  (elixir 1.15.0) src/elixir.erl:283: :elixir.env_for_eval/1
  (elixir 1.15.0) lib/code.ex:998: Code.eval_quoted/3
  (phoenix_storybook 0.5.4) lib/phoenix_storybook/rendering/component_renderer.ex:151: PhoenixStorybook.Rendering.ComponentRenderer.render_component_heex/3
  (phoenix_storybook 0.5.4) lib/phoenix_storybook/live/story_live.ex:419: anonymous fn/3 in PhoenixStorybook.StoryLive.render_content/2
```

3) ```
warning: :functions option in eval is deprecated
  (elixir 1.15.0) src/elixir.erl:291: :elixir.env_for_eval/1
  (elixir 1.15.0) lib/code.ex:998: Code.eval_quoted/3
  (phoenix_storybook 0.5.4) lib/phoenix_storybook/rendering/component_renderer.ex:151: PhoenixStorybook.Rendering.ComponentRenderer.render_component_heex/3
  (phoenix_storybook 0.5.4) lib/phoenix_storybook/live/story_live.ex:419: anonymous fn/3 in PhoenixStorybook.StoryLive.render_content/2
```

**Comment by cblavier** [comment]
thanks, I will get it fixed!

**Comment by cblavier** [comment]
👌

**Comment by shirishgoyal** [comment]
Thanks a lot. When is the release date?

**Comment by cblavier** [comment]
releasing `0.5.5` today!
