### ISSUE TITLE
Export formatter rules for `live_storybook/2`

### ISSUE THREAD

**Issue by LostKobrakai** [phenixdigital/phoenix_storybook#332]
The router macro shouldn't have parentheses added, similar to e.g. `live_dashboard`

**Comment by cblavier** [comment]
I'm not sure what you mean.
Is this related to mix format `locals_without_parens` option?

**Comment by LostKobrakai** [comment]
Yes: https://hexdocs.pm/mix/Mix.Tasks.Format.html#module-importing-dependencies-configuration

**Comment by cblavier** [comment]
can you have a quick look at #351 I just opened?

**Comment by LostKobrakai** [comment]
That's a different thing. I meant phoenix_storybook should export `locals_without_parens` settings for `live_storybook` router macro.

**Comment by LostKobrakai** [comment]
Yeah, phoenix does however: https://github.com/phoenixframework/phoenix/blob/main/.formatter.exs#L74-L75 Not sure exactly why they do it that way, but they do.

**Comment by cblavier** [comment]
good catch! 
I should ask them to add `phoenix_storybook` 😛 
(I will amend my PR with the `locals_without_parens` export)
