### ISSUE TITLE
Hex release not independently compilable

### ISSUE THREAD

**Issue by JTarasovic** [phenixdigital/phoenix_storybook#335]
I'm trying to build a project using `nix` and a tool called [`mix2nix`](https://github.com/ydlr/mix2nix) that compiles each dependency independently. Unfortunately, in this mode, `phoenix_storybook` as a dependency doesn't compile as `config/config.exs` is missing.

```
** (File.Error) could not read file "/home/jason/Development/bi/main/platform_umbrella/deps/phoenix_storybook/config/config.exs": no such file or directory
    (elixir 1.15.4) lib/file.ex:358: File.read!/1
    (elixir 1.15.4) lib/config/reader.ex:110: Config.Reader.read_imports!/2
    (mix 1.15.4) lib/mix/tasks/loadconfig.ex:54: Mix.Tasks.Loadconfig.load_compile/1
    (mix 1.15.4) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.4) lib/mix/cli.ex:91: Mix.CLI.run_task/2
    /nix/store/2h8rz1qa4mv8pj5l79gx34nir2ffr8fx-elixir-1.15.4/bin/mix:2: (file)
```

It's possible to trigger this behavior with any project that has `phoenix_storybook` as a dependency by running `mix deps.get && mix compile` in the directory of the `phoenix_storybook` dependency. I also have a [repo](https://github.com/JTarasovic/mix2nix_storybook_repro) that demonstrates the full problem that we're having.

I'm relatively new to the elixir ecosystem so I'm not sure what the expected behavior is/should be. I'm also not sure why there's no issue when compiling all dependencies but does if you navigate into a single repo and try to compile. /shrug

As this is our only dependency that does this, I wonder if it'd be possible to just publish a/the config?

EDIT; ~as an example, [livebook](https://github.com/livebook-dev/livebook/blob/7bcdd90b666694e3f6582365e0fc645a926bd089/mix.exs#L54) does publish its config folder.~

**Comment by LostKobrakai** [comment]
I'd argue that the approach this is using is not what you want to do. Mix compiles dependendencies rather differently than it compiles root level projects. Trying to treat depedencies like root level projects sounds like an antipattern to me.
