### ISSUE TITLE
`theme` Attribute does not render in the example code

### ISSUE THREAD

**Issue by dsrees** [phenixdigital/phoenix_storybook#352]
If I declare a component with the `attr :theme, :string`, then the variation will properly style the example, but the code block next to the example will not include the `theme`. I haven't had the chance yet to look over the source, but I'm assuming that `theme` may be some special term in storybook.

```elixir
# My functional component
attr :theme, :string, default: "primary"
def button(assigns) do
    ...
end


# In the .story.exs
%Variation{
    id: :button,
    attributes: %{
        text: "Button text",
        theme: "red"
    }
}
```

Resulting storybook file renders as such
![Screen Shot 2023-09-28 at 11 20 59 AM](https://github.com/phenixdigital/phoenix_storybook/assets/2887223/3f834211-e68d-4173-b3d7-3c77f8e2a660)

**Comment by cblavier** [comment]
Hey Daniel,

`theme` as indeed a special meaning in storybook. I recommend you read this [guide](https://hexdocs.pm/phoenix_storybook/theming.html)

But it shouldn't be removed from your code if you are not explicitly using the theming assign strategy.

I'll have a look into it

**Comment by dsrees** [comment]
Thanks @cblavier for pointing out those docs and taking a look. We are not making use of any theming as described. Happy to provide more details if helpful.

**Comment by cblavier** [comment]
I just fixed the issue, would you mind testing your code against storybook's main branch to make sure this is ok now?

(if you have any issues with assets while testing an unreleased version of the library, please make sure you have read https://github.com/phenixdigital/phoenix_storybook#contributing)

**Comment by dsrees** [comment]
👍🏼 Looking good locally. Thanks for quickly resolving this, I appreciate it.


(I didn't bother getting assets to work locally, but the code examples render correctly)
![Screen Shot 2023-10-03 at 11 21 40 AM](https://github.com/phenixdigital/phoenix_storybook/assets/2887223/b88916b9-6008-4c3f-810a-6042968a54aa)
