### ISSUE TITLE
Cannot get any of my own components to display properly in the stories view

### ISSUE THREAD

**Issue by matthewsinclair** [phenixdigital/phoenix_storybook#353]
I am trying to get a very simple pair of components called `Header` and `Footer` to show up in Storybook. Everything is working perfectly out-of-the-box for the default setup with `CoreComponents`, but nothing I do will cause my two components to render properly. If I have a component with anything _other_ than this style of setup:

```elixir
defmodule Storybook.ChromeComponents.Header do
  use PhoenixStorybook.Story, :component
  alias Elixir.MultiplyerWeb.ChromeComponents

  def function, do: &ChromeComponents.header/1

  # def variations do
  #   [
  #     %Variation{
  #       id: :default,
  #       slots: ["Default"]
  #     }
  #   ]
  # end

  def attributes, do: []
  def slots, do: []
  def variations, do: []
end
```

I get the following runtime error when I visit the storybook page for that component:

![Screenshot 2023-09-30 at 17 44 38](https://github.com/phenixdigital/phoenix_storybook/assets/311495/0c6d6c0e-e9f6-48a6-a467-fe80ceea8363)

that is really difficult to debug and work out what has gone wrong.

My Header component is defined as:

```elixir
defmodule MultiplyerWeb.ChromeComponents do
  @moduledoc """
  Provides core UI components for browser chrome.
  """
  use Phoenix.Component
  use MultiplyerWeb, :html

  @doc """
  Renders the default Multiplyer header.

  ## Examples

      <.header/>
  """
  attr :current_user, :string, required: true
  attr :class, :string, default: nil

  def header(assigns) do
    ~H"""
    <header class={["bg-white w-full fixed inset-x-0 top-0 z-0", @class]}>
      ...
    </header>
    """
  end
  ...
```

Note: I renamed `Header` in `CoreComponents` to `Header1` so that it wouldn't clash with my `Header`.

This is what Storybook shows when I don't have a `def variations...` function:

![Screenshot 2023-09-30 at 17 48 33](https://github.com/phenixdigital/phoenix_storybook/assets/311495/813fd2a4-e963-4812-8716-384fd1ece3a1)

Any help here would be much appreciated. Thanks!

**Comment by matthewsinclair** [comment]
Ok, so after some digging, I found the issue. It was that I wasn't properly specifying the attributes in the story. This led to a death spiral that was not reported in an obvious way. I stuck some debug code into a couple of Storyboard modules and I could see that the `attributes:` property was `nil` and this meant that when I referenced one of the attributes in the component, it borked. 

For the record, my Header1 story now looks like this:

```elixir
defmodule Storybook.ChromeComponents.Header1 do
  use PhoenixStorybook.Story, :component
  alias Elixir.MultiplyerWeb.ChromeComponents

  def function, do: &ChromeComponents.header1/1

  def attributes, do: [%Attr{ id: :current_user, type: :map }, %Attr{ id: :class, type: :string}]

  def variations do
    [
      %Variation{
        id: :default,
        description: "Default Header",
        attributes: %{ current_user: %{ email: "hello@multiplyer.app"} },
        slots: []
      }
    ]
  end
end
```

The new problem is that now it all compiles and displays (mostly) properly, but the actual HTML/CSS from the components is not being emitted properly into the Playground | Preview tab. 

This is what I am seeing: 
![image](https://github.com/phenixdigital/phoenix_storybook/assets/311495/66bd9a0c-5b48-4023-92ed-8d0683b1fb33)

I will keep digging ...

**Comment by matthewsinclair** [comment]
Aha! And now I know why the component HTML isn't displaying. It _is_ there, but it's a `<header...>` HTML component, so _of course_ that isn't going to show up inside a random `<div...>` in the middle of the page. 🤦‍♂️

So, this is solved, but now I have an entirely different issue!

**Comment by cblavier** [comment]
coding is walking from one issue to another, it seems you are in the right direction
feel free to open another ticket if you need help, I'm not super fast to answer but I still try to do my best!

**Comment by cblavier** [comment]
ok, let's do that
I'll have a look later this week

**Comment by matthewsinclair** [comment]
Ok, I have added you to the repo. If you start it up on localhost and visit this URL, you will see the problem:

`http://localhost:4000/storybook/live_components/auth_live/auth_form`

```elixir
[debug] compiling storybook file: live_components/auth_live/auth_form.story.exs
[info] Sent 500 in 452ms
[error] #PID<0.1341.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.1340.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /storybook/live_components/auth_live/auth_form
** (exit) an exception was raised:
    ** (TokenMissingError) nofile:1:9571: missing terminator: ] (for "[" starting at line 1)
    |
  1 | %{data: nil, id: "form", name: "form", type: :create, opts: [as: "form", warn_on_unhandled_errors?: true], forms: %{}, params: %{}, resource: Multiplyer...<snip>
```

Let me know how you go. And thanks a ton for doing this!

**Comment by matthewsinclair** [comment]
Wow! My friend, you are a legend! 

It's funny, just before you sent this thru I was looking at the other docs on "Late evaluation" and was wondering what that was all about. 

Thanks again for taking the time here! Very much appreciated.

**Comment by cblavier** [comment]
![image](https://github.com/phenixdigital/phoenix_storybook/assets/130783/82e770da-ff0b-4666-b330-1834d76a9bf5)
