### ISSUE TITLE
How can I add components from different module than CoreComponents?

### ISSUE THREAD

**Issue by drlogout** [phenixdigital/phoenix_storybook#424]
I would like to generate storybook files from my own components in a different module than CoreComponents, for example a module called DemoWeb.SiteComponents.

I can't find anything in the documentation, is this possible?

Thanks!
Chris

**Comment by cblavier** [comment]
Hey Chris,

of course, you can showcase any components other than CoreComponents.

I can suggest you to have a look at the demo storybook repository, available here: https://github.com/phenixdigital/phoenix_storybook_demo

Custom components have been created in `lib/phoenix_storybook_demo/components`
