### ISSUE TITLE
Components that take callback fns

### ISSUE THREAD

**Issue by trashhalo** [phenixdigital/phoenix_storybook#477]
A common pattern in our codebase is components that take fn from parent to let components pass data/events up. This pattern is detailed in the live view documentation here. https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-unifying-liveview-and-livecomponent-communication

Is it possible to model this with a component story? Ideally there would be a similar facility to Psb assigns/toggle for inter component comms.

**Comment by trashhalo** [comment]
I think if this code existed in a handle info I could send(self(), to change assigns. https://github.com/phenixdigital/phoenix_storybook/blob/main/lib%2Fphoenix_storybook%2Flive%2Fstory_live.ex#L637

**Comment by noozo** [comment]
+1

**Comment by cblavier** [comment]
hey @trashhalo 
it would help if you could write a gist with a component example and a story as you would like to write it

**Comment by cblavier** [comment]
closing for now, feel free to reopen if you can give me more details
