### ISSUE TITLE
Boolean rendering seems to be broken + `nil`.

### ISSUE THREAD

**Issue by sodapopcan** [phenixdigital/phoenix_storybook#482]
Hey Christian!

Thanks so much for Storybook, it's very awesome.

Related to this #169, this appears not to be working anymore.  I'm seeing `attr={true}` in all my components.  Furthermore, would it be possible to ignore any attributes that are `nil` as this is how HEEx works (passing `nil` to an attribute will not render the whole attribute).  I was looking for a setting for this but can't seem to find it.

Thanks again,
Andrew

**Comment by cblavier** [comment]
hey there 👋

this is weird, as this shorthand boolean rendering does seem to work properly [here](https://phoenix-storybook-demo.fly.dev/storybook/components/badge?tab=playground&theme=default&variation_id=default_badge) and is thoroughly tested in [this file](https://github.com/phenixdigital/phoenix_storybook/blob/main/test/phoenix_storybook/rendering/code_renderer_test.exs#L218)

Are your attributes properly declared as boolean before your function component? 
https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#module-attributes

I will have a look at nil attributes, I'm not sure this is properly handled

**Comment by cblavier** [comment]
Hey, did you get a chance to take a look?

**Comment by sodapopcan** [comment]
Sorry, no I have not as I have a bunch on my list and this is a "nice to have."  I'm still planning on a PR, though.

**Comment by cblavier** [comment]
sure, feel free to reopen whenever you want
