### ISSUE TITLE
Modal component using `.showModal()` does not work due to variation_id not being a valid javascript variable

### ISSUE THREAD

**Issue by noozo** [phenixdigital/phoenix_storybook#495]
I have a modal component with an optional CTA button to open it via JS, using the dialog element method (with onclick):

```
<button
        :if={slot_assigned?(assigns, :cta)}
        type="button"
        onclick={"#{@id}.showModal();"}
        class={@cta_button_class}
      >
```

The problem is that the generated id will not be a valid JS variable name, and the showModal function will fail when i click the CTA button in a story:

![image](https://github.com/user-attachments/assets/1f913c51-dc06-4654-9be4-ad61fcfb4e4f)

This is the generated id, shown when clicking the error in the JS console:
```
modal-single-cta.showModal();
```

**Comment by noozo** [comment]
Got around it by explicitly defining the variation id in the template of the variation:

```
%Variation{
        id: :cta,
        attributes: %{},
        slots: [
          """
           This is my modal text
           <:cta>Click this CTA</:cta>
          """
        ],
        template: """
          <.psb-variation id="cta_modal" />
        """
      },
```

**Comment by cblavier** [comment]
this is the way to go, remember that you can also
