### ISSUE TITLE
Problem with using tailwind classes in the playground.

### ISSUE THREAD

**Issue by jhonathas** [phenixdigital/phoenix_storybook#505]
Hello,

Yesterday I installed StoryBook for the first time and noticed that when I use the playground to apply class changes to a component, it doesn't work. It seems to me that it only works with Tailwind classes that are already in use in the application; any new class is not recognized.

Does anyone have any tips on what I can do to solve this?

**Comment by cblavier** [comment]
Hey @jhonathas 

indeed, any class not present in the sources won't be bundled by the Tailwind JIT.

You can workaround the issue by _safe listing_ some classes like in this file: https://github.com/phenixdigital/phoenix_storybook_demo/blob/ec54fd2e7b99a254cfd77cfda5ac06c35cfc836f/assets/tailwind.config.js#L16

Hope this helps

**Comment by jhonathas** [comment]
Thank you. I'll test it.

**Comment by cblavier** [comment]
Were you able to test it?

**Comment by jhonathas** [comment]
@cblavier I ended up missing your question. I haven't tested it yet - I believe that if I do this I will have another problem which is generating larger CSS for things that I didn't even use in the APP code - I will come back to this topic and see if I can do it in other ways.

**Comment by err0r500** [comment]
I stumbled on the same problem this morning. I ended up creating a fake component in my app where I list all the icons I use / want to see in storybook

**Comment by cblavier** [comment]
Do you think it's better than the Tailwind safelist approach?

https://github.com/phenixdigital/phoenix_storybook/issues/505#issuecomment-2402690964

**Comment by err0r500** [comment]
I just tried the "safelist" approach. It may be a bit cleaner actually (and the idea is the same)
