### ISSUE TITLE
Component docs are unstyled

### ISSUE THREAD

**Issue by xxdavid** [phenixdigital/phoenix_storybook#514]
Hi, first of all, thanks for this awesome library! It's a game changer!

I have a few issues related to components docs, so I am going to create an issue for each of them. The first thing is that component docs are completely unstyled.

For example, if I use the following docs for `PhoenixStorybookDemo.Components.Button.button/1`

```elixir
  @doc """
  A simple button. When clicked, triggers a `boom` event.

  This button is:
  * great
  * awesome
  * stylish

  ## Example

      <button label="Click me" />
  """
```

then it looks like this in the Storybook:

![Screenshot 2024-11-26 at 13 50 23](https://github.com/user-attachments/assets/5e78a8d1-1ad2-45c0-ace0-d70ac38a4e4f)

Notice that the list does not have any bullets and the heading looks just like normal text.

It is due to the Tailwind Preflight which is effective on the whole page, including the docs. I think, something like the `prose` class from [Tailwind Typography](https://github.com/tailwindlabs/tailwindcss-typography) should be used on the docs. In our company's Storybook, we are currently using this hackish workaround in our CSS:

```css
  #doc-next h2 {
    @apply text-lg font-semibold;
  }

  #doc-next h3, h4, h5, h6 {
    @apply font-semibold;
  }

  #doc-next ul {
    @apply list-disc list-inside;
  }

  #doc-next code.inline {
    @apply py-[.1em] px-[.2em] bg-[#f8fafc] border rounded-sm;
  }

  #doc-next pre code {
    @apply block py-2 px-4 bg-[#f8fafc] border rounded-sm;
  }

  #doc-next a {
    @apply text-blue-600 hover:text-blue-500;
  }
```

I believe something like this (probably more elaborated, e.g., with different styles for h3 and h4) should be baked directly into Storybook, so that the docs are formatted out-of-the-box. What do you think?

**Comment by cblavier** [comment]
work in progress

![CleanShot 2024-12-05 at 19 26 55](https://github.com/user-attachments/assets/a636f3e0-b9e3-4864-822c-03bc68c84a8a)

can't make syntax coloring work though

**Comment by xxdavid** [comment]
Wow, looks awesome!

**Comment by sodapopcan** [comment]
Hey @cblavier!

I didn't re-read my [Elixir Forum](https://elixirforum.com/t/earmark-parsing-html-inside-code-blocks/50269) post very carefully.  I was able to get Tailwind classes inside markdown though it has been a while.  It is coming back to me that there was something about Floki that was causing new lines and therefore messing up the formatting.  If you aren't working on it right now (I know it's getting late there), I'd be happy to giver it a go this evening!

**Comment by SteffenDE** [comment]
Note that with 

```
  @doc """
  A simple button. When clicked, triggers a `boom` event.

  This button is:
  * great
  * awesome
  * stylish

  ## Example

      <button label="Click me" />
  """
```

the example is also not properly highlighted in ExDoc, you'll probably want to use

    @doc """
    A simple button. When clicked, triggers a `boom` event.

    This button is:
    * great
    * awesome
    * stylish

    ## Example

    ```heex
    <button label="Click me" />
    ```
    """

then it is clear that HEEx syntax should be used when highlighting, which could probably be helpful.

**Comment by cblavier** [comment]
> Hey @cblavier!
> 
> If you aren't working on it right now (I know it's getting late there), I'd be happy to giver it a go this evening!

It was late indeed 😉
Please give it a go!
