### ISSUE TITLE
Stripping attributes from component docs feels weird

### ISSUE THREAD

**Issue by xxdavid** [phenixdigital/phoenix_storybook#515]
In component docs, everything after the *Attributes* heading is hidden/stripped:

https://github.com/phenixdigital/phoenix_storybook/blob/5a8df65af4e97948c00de88f8d47c3bd4dfe1dad/lib/phoenix_storybook/stories/doc.ex#L75-L77

This feels weird to me for several reasons:
* If I use `[INSERT LVATTRDOCS]` in the middle of the docs, everything below it gets hidden; note that this is a common practice, see for example [`Phoenix.Component.live_title/1`](https://github.com/phoenixframework/phoenix_live_view/blob/d1901861e90fb60ab26326e213ec18f92b5d06da/lib/phoenix_component.ex#L2086)
* If I use only slots and no attributes, the slots show up in the docs; If I use both slots and attributes, slots do not show up in the docs
* If I define include `## Attributes` in the docs (for example in the docs for a Live Component, as they don't support the `attr/3` macro), the paragraph and everything below gets hidden

Additionally, it feels really magic, when for example adding some attributes hides the slots paragraph.

I guess that the reason for hiding Attributes (and Slots) in the docs is that they are also shown in the Playground tab. Personally, I don't mind showing them at two places, and would even appreciate if they were in the docs so they would be visible alongside other information related to the component. What's you opinion on this?

**Comment by cblavier** [comment]
It wasn't such a good idea after all 😅 
Many edge cases were not effectively handled by the stripping regex.

Documentation will still be stripped from attributes by default.
This behaviour can be disabled with the following storybook option: `strip_doc_attributes: false`

**Comment by xxdavid** [comment]
Yeah, the option sounds like a good solution to me. 🙁
