### ISSUE TITLE
Functions provided as arguments not passed to component

### ISSUE THREAD

**Issue by krilllind** [phenixdigital/phoenix_storybook#536]
## Summary
When rendering a component with arguments accepting a function, storybook strips this and only assigns `nil`.

Based on this recommendation from the Phoenix framework this is a valid approach for unified communication, it works fine but just not in Storybook.

Ref: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-unifying-liveview-and-livecomponent-communication

## Steps to reproduce
Create a component:
```ex
defmodule Test do
  use Phoenix.component

  attr(:func, :any)

  def render(assigns) do
    ~H"""
      <p><%= func.("hello world")  %></p>
    """
  end
end
```
Storybook:
```ex
defmodule Storybook.Test do
  use PhoenixStorybook.Story, :live_component

  def component, do: Test

  def variations do
    [
      %Variation{
        id: :default,
        attributes: %{
          func: fn _ -> "override text" end
        }
      },
      %Variation{
        id: :default,
        attributes: %{
          func: &display_something/1
        }
      },
    ]
  end

  defp display_something(_item), do: "override text"
end
```

## Expected
To see the function being called and having my custom text returned

## Actual Result
Error is returned because function is `nil`

```
** (exit) an exception was raised:
    ** (BadFunctionError) expected a function, got: nil

**Comment by cblavier** [comment]
I never envisaged passing functions as assigns, but I agree it should work.
I'll see what I can do

**Comment by cblavier** [comment]
You can make it work using [late evaluation](https://github.com/phenixdigital/phoenix_storybook/blob/main/guides/components.md#late-evaluation)

```elixir
defmodule PhoenixStorybookDemo.Components.Function do
  use PhoenixStorybook.Story, :component
  alias PhoenixStorybookDemo.Components.{Function, FunctionComponent}

  def function, do: &FunctionComponent.fun/1

  def variations do
    [
      %Variation{
        id: :anonymous_function,
        attributes: %{
          func: {:eval, ~s|fn _ -> "override text" end|}
        }
      },
      %Variation{
        id: :local_function,
        attributes: %{
          func: {:eval, ~s|&#{Function}.display_something/1|}
        }
      }
    ]
  end

  def display_something(_item), do: "override text"
end
```

![CleanShot 2024-12-16 at 13 24 50](https://github.com/user-attachments/assets/c9d543fc-9986-414b-a81f-e70580ad69d1)

Let me know if this is working for you.
You can then go ahead and close the issue.

**Comment by cblavier** [comment]
Is it working for you?
I was able to test it again on core_component's table function, it was doing okay 👌 

Feel free to reopen if necessary
