### ISSUE TITLE
Upgrade Phoenix LiveView to 1.0

### ISSUE THREAD

**Issue by chvanikoff** [phenixdigital/phoenix_storybook#537]
Hi there!

Phoenix LiveView 1.0 just came out! Would you consider updating the dependency?
Thanks for your amazing work on this project! 🙌

**Comment by cblavier** [comment]
Hey Roman,

yes this is planned, I usually wait for one or two minor updates before updating dependencies.
do you know if there are any breaking changes?

**Comment by cblavier** [comment]
I updated the dependency to 1.0.1 on the [demo application](https://github.com/phenixdigital/phoenix_storybook_demo).

It works flawlessly
Did you experience any issue?

**Comment by chvanikoff** [comment]
Yep, they do have breaking changes: dropped the support for `phx-feedback-for` annotations, `live_flash`, and `push_redirect`. There was something else minor, related to dynamic tags handling... But after a quick look at the phoenix_storybook code, I couldn't find any dependency on the deprecated functions. So, it looks to me the migration shouldn't be painful, but, as author, you should still check the [changelog](https://github.com/phoenixframework/phoenix_live_view/blob/main/CHANGELOG.md) and confirm compatibility.

They also added inline interpolation as opposed to embedded expressions so you can write `hi {@user.name}` instead of `hi <%= @user.name %>` now. But that one is backward compatible and doesn't require immediate update when upgrading to LV1.0.

**Comment by cblavier** [comment]
I didn’t notice any breaking changes in the changelog, and I didn’t experience any issues with the demo app. 

Could you clarify what you expect from me?

I believe keeping the dependency as `{:phoenix_live_view, "> 0.18.7"}` allows users to decide whether they want to use the latest version of LiveView or not.

**Comment by chvanikoff** [comment]
If you want to use the new interpolation syntax, then it should be ~> 1.0.1, otherwise if you're ok with using `<%=` embedded expressions, it would probably make sense to set the dependency as `or`: `~> 0.18.7 or ~> 1.0.1`. `>` could introduce compatibility issues if there was a new version to come out with breaking changes affecting the storybook codebase.

**Comment by cblavier** [comment]
I'm sorry, I feel a bit stupid, but it seems we don't manage to understand each other 😅 

The current `phoenix_live_view` dependency declared in `phoenix_storybook`  is `"> 0.18.7"`  
There is no `~>` in it.
So you can use `0.18.x`, `0.20.x` or `1.0.x` without any issue

`phoenix_storybook` codebase itself will be updated to use the new embedded expression syntax in a couple of weeks.

**Comment by chvanikoff** [comment]
hm, now it's time for me to feel stupid - I saw dependency compatibility issue in my project when installed storybook, and quickly judged the storybook to be the problem because I read `~> 0.18` instead of `> 0.18`. But now I see that's not the case and my issue was very likely somewhere else. I will try enabling storybook in my app once again and I guess it should just work. Sorry for the false alarm, I'm closing this issue.

**Comment by chvanikoff** [comment]
@cblavier found/remembered the issue, it was with storybook indeed, I just forgot what it was 😅
here are the compiled assets https://preview.hex.pm/preview/phoenix_storybook/0.7.2/show/priv/static/js/app-752894c2093944cc7d8585668b225d03.js and the problem is that the assets are compiled with LV 0.20.17 (version() function returns "0.20.17"), which results in mismatch between client and server liveview versions:
<img width="635" alt="Screenshot 2024-12-17 at 5 31 05 PM" src="https://github.com/user-attachments/assets/9804be68-041e-4398-9d72-eda272c4efc5" />
its not obvious to me how to support both versions unless you can delegate assets compilation to end user

**Comment by chvanikoff** [comment]
Awesome, thank you!

**Comment by cblavier** [comment]
thanks for the tip ❤️
