### ISSUE TITLE
source tab includes extra lines with render_only_function_source

### ISSUE THREAD

**Issue by chvanikoff** [phenixdigital/phoenix_storybook#541]
Hi, I read the code and see the limitation being that we only know about function starting line, but not its end line. I'd suggest to use the next function start line not as the current one's ending, but as a marker to look backwards to find `end` and consider that to be the last line of the current function.

```elixir
max_line..start_line
|> Enum.find(max_line, fn line ->
  source_lines
  |> Enum.at(line)
  |> String.trim()
  |> Kernel.==("end")
end)
```

I tested this locally - seems to get the job done well. Happy to submit a PR if this looks good to you.

**Comment by cblavier** [comment]
Please open a PR 👍
If it improves the current behavior you should add a test case to `story_source_test.exs`

**Comment by chvanikoff** [comment]
closed by #542 😊

**Comment by cblavier** [comment]
btw I'm removing the `render_only_function_source/0` function.
You will now have to add this in your story

```elixir
defmodule Storybook.Components.Breadcrumb do
  use PhoenixStorybook.Story, :component

  def render_source, do: :function

  # ...
end
```

It can be either set to `:module` (default), `:function` or false (disables the source tab)

**Comment by chvanikoff** [comment]
fine with me, as long as we have an option to not include all functions of a module in the source tab
