### ISSUE TITLE
Rename the project & repo to phoenix_storybook

### ISSUE THREAD

**Issue by cblavier** [phenixdigital/phoenix_storybook#80]
`phoenix_storybook` / `PhoenixStorybook` everywhere

**Comment by f0rest8** [comment]
Is this still needed? Considering adding phoenix_storybook to our company's codebase for a new UI design but we also need it to support components across the entire project, not just live view, per #187. Happy to help out if I can

**Comment by cblavier** [comment]
Hey 👋

Sure you can use it on any component, not only live_component (that's why the current project name is misleading)
